index:
  path: /
  controller: App\Controller\IndexController::index
film:
  path: /film/{id}
  controller: App\Controller\FilmController::showFilm
login:
  path: /login
  controller:  App\Controller\UserController::login
category:
  path: /category/{id}
  controller:  App\Controller\CategoryController::showFilms
user:
  path: /user/{id}
  controller: App\Controller\UserController::showUserDetails
ranking:
  path: /top/{ranking}
  controller: App\Controller\RankingController::showRanking
newCategory:
  path: /new/{category}
  controller: App\Controller\CategoryController::addCategory
categories:
  path: /category
  controller: App\Controller\CategoryController::showCategories
categoryFilter:
  path: /category/filter/{letter}
  controller: App\Controller\CategoryController::filterCategory

